import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { sendScheduleEmail } from '@/lib/email';
import { getDatesInRange } from '@/lib/date-utils'; // Need to ensure availability or duplicate logic if simpler

export const dynamic = 'force-dynamic';

export async function POST(request: NextRequest) {
    try {
        const tenantKey = request.headers.get('x-user-tenant-key');
        if (!tenantKey) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

        const body = await request.json();
        const { weekRange, htmlTable } = body;
        // Note: Receiving HTML from client is risky for XSS if not careful, 
        // but this is an internal admin tool. 
        // Ideally we generate HTML server side, but recreating the complex table here is hard.
        // We will accept the table HTML generated by the client for now as it's an MVP feature requested by user "table of today/week".

        if (!weekRange || !htmlTable) {
            return NextResponse.json({ error: 'Dati mancanti' }, { status: 400 });
        }

        // Fetch all active staff emails
        const staff = await prisma.staff.findMany({
            where: { tenantKey, email: { not: null } },
            select: { email: true }
        });

        const emails = staff.map(s => s.email).filter(e => e && e.includes('@')) as string[];

        if (emails.length === 0) {
            return NextResponse.json({ error: 'Nessun dipendente con email valida trovato.' }, { status: 400 });
        }

        // Also add the Admin (requester) to the list if they aren't in staff
        const requesterEmail = request.headers.get('x-user-email');
        if (requesterEmail && !emails.includes(requesterEmail)) {
            emails.push(requesterEmail);
        }

        const result = await sendScheduleEmail(emails, htmlTable, weekRange, tenantKey);

        if (!result.success) {
            return NextResponse.json({ error: result.error }, { status: 500 });
        }

        return NextResponse.json({ success: true, count: emails.length });

    } catch (error: any) {
        console.error('Broadcast error:', error);
        return NextResponse.json({ error: 'Errore interno' }, { status: 500 });
    }
}
